name: File Size

on: [pull_request]

jobs:
  build_master:
    name: Build Master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: volta-cli/action@v4
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: master-dist
          path: dist

  build_pr:
    name: Build PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: pr-dist
          path: dist

  report:
    name: Report Sizes
    runs-on: ubuntu-latest
    needs: [build_master, build_pr]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: master-dist
          path: master-dist
      - uses: actions/download-artifact@v4
        with:
          name: pr-dist
          path: pr-dist
      - name: Get size of Master
        id: master-size
        run: |
          echo "base=$(du -b master-dist/index.js | cut -f1)" >> $GITHUB_OUTPUT
          echo "modern=$(du -b master-dist/index.modern.js | cut -f1)" >> $GITHUB_OUTPUT
          echo "module=$(du -b master-dist/index.module.js | cut -f1)" >> $GITHUB_OUTPUT
          echo "umd=$(du -b master-dist/index.umd.js | cut -f1)" >> $GITHUB_OUTPUT
      - name: Get size of PR
        id: pr-size
        run: |
          echo "base=$(du -b pr-dist/index.js | cut -f1)" >> $GITHUB_OUTPUT
          echo "modern=$(du -b pr-dist/index.modern.js | cut -f1)" >> $GITHUB_OUTPUT
          echo "module=$(du -b pr-dist/index.module.js | cut -f1)" >> $GITHUB_OUTPUT
          echo "umd=$(du -b pr-dist/index.umd.js | cut -f1)" >> $GITHUB_OUTPUT
      - name: Post Comment
        if: steps.master-size.outputs.base != steps.pr-size.outputs.base
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            | Build | Base | Modern | Module | UMD |
            | :-- | :-- | :-- | :-- | :-- |
            | `master` | ${{ steps.master-size.outputs.base }} B | ${{ steps.master-size.outputs.modern }} B | ${{ steps.master-size.outputs.module }} B | ${{ steps.master-size.outputs.umd }} B |
            | PR Size | ${{ steps.pr-size.outputs.base }} B | ${{ steps.pr-size.outputs.modern }} B | ${{ steps.pr-size.outputs.module }} B | ${{ steps.pr-size.outputs.umd }} B |
